services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_DATABASE: aplikasi-leave-request-management
      DB_USERNAME: postgres
      DB_PASSWORD: darkvenus05

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: aplikasi-leave-request-management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: darkvenus05
    ports:
      - "5432:5432"