services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_DATABASE: (isi dengan nama database postgree kalian)
      DB_USERNAME: postgres
      DB_PASSWORD: (isi dengan password postgree kalian)

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: (isi dengan nama database postgree kalian)
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: (isi dengan password postgree kalian)
    ports:
      - "5432:5432"
